.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. graincoin_qt test_graincoin_qt
clean: FORCE
	$(MAKE) -C .. graincoin_qt_clean test_graincoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_graincoin_qt_check
graincoin-qt graincoin-qt.exe: FORCE
	 $(MAKE) -C .. graincoin_qt
